---
title: "bandit solution"
author: "Mohammed Hejairi"
date: "`r Sys.Date()`"
output: html_document
---

# Epsilon-Greedy Function
```{r}
run_bandit <- function(epsilon, n_steps) {

  p_true <- c(0.10, 0.50, 0.20, 0.05, 0.30)
  K <- length(p_true)

  Q <- rep(0, K)
  N_arm <- rep(0, K)

  rewards <- rep(0, n_steps)

  for (t in 1:n_steps) {

    u <- runif(1)

    if (u < epsilon) {
      arm <- sample(1:K, 1)
    } else {
      arm <- which.max(Q)
    }

    reward <- rbinom(1, 1, p_true[arm])

    N_arm[arm] <- N_arm[arm] + 1
    Q[arm] <- Q[arm] + (1 / N_arm[arm]) * (reward - Q[arm])

    rewards[t] <- reward
  }

  cumulative_avg_reward <- cumsum(rewards) / (1:n_steps)

  return(cumulative_avg_reward)
}
```



# Simulation

```{r}
N <- 10000
epsilon <- 0.1
avg_reward <- run_bandit(epsilon, N)
```


# Plot

```{r}
plot(
avg_reward,
type = "l",
col = "blue",
lwd = 2,
xlab = "Iteration",
ylab = "Average Reward",
main = "Epsilon-Greedy Bandit Performance (ε = 0.1)"
)
abline(h = 0.5, col = "red", lty = 2, lwd = 2)
legend(
"bottomright",
legend = c("Cumulative Average Reward", "Optimal CTR = 0.50"),
col = c("blue", "red"),
lty = c(1, 2),
lwd = 2
)
```



# Run experiments for multiple ε values
```{r}

epsilons <- c(0.01, 0.1, 0.5)
results <- list()

for (eps in epsilons) {
results[[as.character(eps)]] <- run_bandit(eps, N)
}
```

# Plot all curves together

```{r}
plot(
results[["0.01"]],
type = "l",
col = "blue",
lwd = 2,
xlab = "Iteration",
ylab = "Cumulative Average Reward",
main = "Effect of ε on Epsilon-Greedy Performance"
)
lines(results[["0.1"]], col = "green", lwd = 2)
lines(results[["0.5"]], col = "orange", lwd = 2)
abline(h = 0.5, col = "black", lty = 2, lwd = 2)
legend(
"bottomright",
legend = c("ε = 0.01", "ε = 0.1", "ε = 0.5", "Optimal CTR = 0.5"),
col = c("blue", "green", "orange", "black"),
lty = c(1, 1, 1, 2),
lwd = 2
)
```

